print("Python sorting practice!")

countries = ["Vietnmam", "Thailand", "Cambodia", "Peru", "Alaska"]
print(countries)
print("My list using sorted method:")
print(sorted(countries))
print("My list as original:")
print(countries)
print("My list in alphabetical reverse order using sort = true method:")
countries.sort(reverse=True)
print(countries)
print("My list as original:")
print(countries)
print("Countries in reverse order using reverse method:")
countries.reverse()
print(countries)
print("Length of countries:")
print(len(countries))
